services:
  - type: web
    name: samanvay-backend
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    envVars:
      - key: SAMANVAY_DATABASE_URL
        fromDatabase:
          name: samanvay-db
          property: connectionString
      - key: SAMANVAY_CORS_ORIGINS
        value: https://samanvay-frontend.onrender.com
    autoDeploy: true

  - type: web
    name: samanvay-frontend
    runtime: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: VITE_API_BASE
        value: https://samanvay-backend-5g8b.onrender.com/api
    autoDeploy: true

databases:
  - name: samanvay-db
    plan: free
    databaseName: samanvay
    user: samanvay
